# Generated by Django 4.0.5 on 2022-07-04 16:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('video_url', models.URLField(verbose_name='URL do vídeo')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='início')),
                ('end_date', models.DateTimeField(verbose_name='término')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
            ],
            options={
                'verbose_name': 'participante',
                'verbose_name_plural': 'participantes',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.TextField(unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.participant')),
            ],
            options={
                'verbose_name': 'voto',
                'verbose_name_plural': 'votos',
            },
        ),
    ]
